# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in jekyll-kuma-plugins.gemspec
gemspec

gem "rake", "~> 13.3.0"
gem "rspec", "~> 3.13.1"
gem "csv", "3.3.5"
gem "base64", "0.3.0"
gem "bigdecimal", "3.3.1"
