# frozen_string_literal: true

module Jekyll
  class Versions < Jekyll::Generator
    priority :normal

    def generate(site)
      latest_version = latest_version(site.data['versions'])
      site.data['latest_version'] = latest_version

      # Versions present in versions.yml but lacking a docs_nav_kuma_<version>.yml
      # would have no generated pages (404) and an empty sidebar. Fall back to the
      # dev nav so a freshly-added version is navigable until its own nav lands.
      generate_missing_version_navs(site)

      # Add a `version` property to every versioned page
      # TODO: Also create aliases under /latest/ for all x.x.x doc pages
      site.pages.each do |page|
        next unless page.url.start_with?('/docs/')

        release = release_for(page)

        page.data['nav_items'] = {}

        next unless release

        page.data['doc'] = true
        page.data['has_version'] = true

        page.data['release'] ||= release.to_liquid
        page.data['version'] ||= release.default_version
        page.data['version_data'] = release.to_h
        page.data['latest_version'] = edition(site).latest_release.to_h

        # This will be removed once jekyll-single-site-generator stops discarding very new versions when use `{%version  lte:unreleasedVersion %}`
        page.data['nav_items'] = site.data["docs_nav_kuma_#{release.value.gsub('.', '')}"]

        # Clean up nav_items for generated pages as there's an
        # additional level of nesting
        page.data['nav_items'] = page.data['nav_items']['items'] if page.data['nav_items'].is_a?(Hash)
      end
    end

    private

    # For every non-dev version in versions.yml without its own
    # docs_nav_kuma_<version>.yml, generate pages and a sidebar from the dev nav.
    def generate_missing_version_navs(site)
      dev = site.data['versions'].detect { |v| v['label'] == 'dev' }
      return unless dev

      dev_nav = site.data[nav_key(dev['release'])]
      return unless dev_nav

      generator_config = Jekyll::GeneratorSingleSource::GeneratorConfig.new(site)

      site.data['versions'].each do |version|
        next if version['label'] # labeled releases (e.g. dev) are generated by the gem

        release = version['release']
        key = nav_key(release)
        next if site.data[key] # version has its own nav already

        # The update-docs job syncs a version's raw assets (crds/protos/rbac)
        # together with its versions.yml entry, so they are normally present when
        # only the nav lags. If a version was added far ahead of its assets,
        # skip it: keep the old behaviour (no pages) instead of breaking the
        # whole build on the missing assets its pages would load.
        next unless version_assets?(site, release)

        # Expose the dev nav under this version so the sidebar renders.
        site.data[key] = dev_nav

        # Generate the version's pages from the dev nav config, retargeted at
        # this release so URLs and version gating resolve to the right version.
        nav_config = generator_config.build_docs_nav(edition: dev['edition'], release: dev['release'])
        nav_config.config['release'] = release
        nav_config.generate_pages

        Jekyll.logger.warn(
          'Versions:',
          "missing docs_nav for #{release}, generated pages and sidebar from dev (#{dev['release']})"
        )
      end
    end

    # True when the version's generated raw assets exist in any configured path,
    # matching how schema_viewer/rbacresources resolve <base>/<release>/raw/<file>.
    def version_assets?(site, release)
      base_paths = site.config.fetch('mesh_raw_generated_paths', ['app/assets'])
      base_paths.any? { |base| Dir.exist?(File.join(base, release, 'raw')) }
    end

    def nav_key(release)
      "docs_nav_kuma_#{release.gsub('.', '')}"
    end

    def latest_version(versions)
      latest_versions = versions.select { |v| v['latest'] }
      raise "Exactly one entry in app/_data/versions.yml must be marked as 'latest: true' (#{latest_versions.size} found)" if latest_versions.size != 1

      latest_versions.first
    end

    def edition(site)
      @edition ||= Jekyll::GeneratorSingleSource::Product::Edition
                   .new(edition: 'kuma', site: site)
    end

    def release_for(page)
      parts = Pathname(page.url).each_filename.to_a

      edition(page.site).releases.detect { |r| r.to_s == parts[1] }
    end
  end
end
