name: project-lifecycle
on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:
  issues:
    types:
      - reopened
      - opened
      - labeled

jobs:
  lifecycle:
    uses: kumahq/.github/.github/workflows/wfc_lifecycle.yml@d266a5173018b554838bc167fedd4a2bd08add64
    with:
      filesToIgnore: CODEOWNERS,CONTRIBUTING.md
