name: Lint and test tools
on:
  push:
    branches: [master]
    paths: [tools/**]
  pull_request:
    paths: [tools/**]
jobs:
  lint-and-test-tools:
    name: Lint and test tool scripts
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Shellcheck
        run: mise shellcheck
      - name: Run tool tests
        run: mise test:tools
