name: Test Plugins
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
jobs:
  test-plugins:
    runs-on: ubuntu-24.04
    steps:
      - name: Check relevant changes
        id: changes
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        with:
          filters: |
            plugins:
              - 'jekyll-kuma-plugins/**'
              - 'app/_plugins/**'
              - 'spec/**'
              - '.rubocop.yml'
              - '.github/workflows/test-plugins.yml'
              - 'mise.toml'
      - name: Checkout
        if: steps.changes.outputs.plugins == 'true'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup mise
        if: steps.changes.outputs.plugins == 'true'
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Rubocop
        if: steps.changes.outputs.plugins == 'true'
        uses: reviewdog/action-rubocop@b6d5e953a5fc0bf3ab65254e77730ea2174d6d6d # v2.22.0
        with:
          reporter: github-pr-check
          fail_level: error
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Test jekyll-kuma-plugins
        if: steps.changes.outputs.plugins == 'true'
        run: mise run test:plugins
      - name: Test spec
        if: steps.changes.outputs.plugins == 'true'
        run: mise run install && mise run test
